#!/usr/bin/ansible-playbook -K

# Specialized setup for plexy host.
# Just run as a script: `./plexy.yml`
---
- hosts: localhost
  tasks:
    - include_role:
        name: bootstrap
    - include_role:
        name: logseq
    - include_role:
        name: etckeeper
    - include_role:
        name: sysstat
    - include_role:
        name: restic
