#!/usr/bin/ansible-playbook -K

# Specialized setup for plexy host.
# Just run as a script: `./plexy.yml`
---
# Include the common bootstrap.
- name: Include a play after another play
  ansible.builtin.import_playbook: setup-local.yml

# Plexy specific roles.
# - hosts: localhost
#   tasks:
#     - include_role:
#         name: restic
