#!/usr/bin/ansible-playbook -K
#
# General setup that applies to all systems
# Just run as a script: `./setup-local.yml`
---
- hosts: localhost
  tasks:
    - include_role:
        name: bootstrap
    - include_role:
        name: etckeeper
    - include_role:
        name: sysstat
    - include_role:
        name: logseq
    - name: "Enable sysreq magic keys"
      become: true
      ansible.builtin.copy:
        content: |
          kernel.sysrq=1
        dest: /etc/sysctl.d/90-sysrq.conf
        owner: root
        group: root
        mode: '0644'
