---
- name: Ensure Flatpak is installed
  become: true
  ansible.builtin.package:
   name: flatpak
   state: present

- name: Add Flathub remote repository
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system 
